openeuropa/oe_list_pages

- composer.json
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OPENEUROPA-0000: Fix emr patch.

- src/Plugin/facets/widget/ListPagesMultiselectWidget.php
- src/Plugin/facets/widget/ListPagesWidgetBase.php
- tests/Kernel/FulltextWidgetTest.php
- tests/Kernel/ListsSourceBaseTest.php
- tests/Kernel/MultiSelectWidgetTest.php
- tests/modules/oe_list_pages_filters_test/config/install/search_api.index.node.yml
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-40: List facet widget

- src/Plugin/facets/widget/MultiselectWidget.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-210: Fixes on multiselect widget.

- config/schema/oe_list_pages.schema.yml
- src/Form/ListFacetsForm.php
- src/ListBuilder.php
- src/ListSourceFactory.php
- src/Plugin/EntityMetaRelation/ListPage.php
- tests/modules/oe_list_pages_filters_test/config/install/core.entity_form_display.node.content_type_one.default.yml
- tests/modules/oe_list_pages_filters_test/config/install/core.entity_form_display.node.content_type_two.default.yml
- tests/modules/oe_list_pages_filters_test/config/install/facets.facet.list_facet_source_node_content_type_twostatus.yml
- tests/modules/oe_list_pages_filters_test/config/install/node.type.content_type_one.yml
- tests/modules/oe_list_pages_filters_test/config/install/node.type.content_type_two.yml
- tests/src/FunctionalJavascript/ListPagesExposedFiltersTest.php
- tests/src/FunctionalJavascript/ListPagesFiltersTest.php
- tests/src/Kernel/ListsSourceTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-223: Default exposed filters.

- modules/oe_list_page_content_type/README.md
- modules/oe_list_page_content_type/config/install/node.type.oe_list_page.yml
- modules/oe_list_page_content_type/oe_list_page_content_type.info.yml
- modules/oe_list_page_content_type/oe_list_page_content_type.install
- runner.yml.dist
- tests/modules/oe_list_pages_filters_test/config/install/core.entity_view_display.node.oe_list_page.default.yml
- tests/modules/oe_list_pages_filters_test/oe_list_pages_filters_test.info.yml
- tests/src/FunctionalJavascript/ListPagesExposedFiltersTest.php
- tests/src/FunctionalJavascript/ListPagesFiltersTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-46: Content type oe_list_page

- src/Plugin/facets/query_type/Fulltext.php
- tests/modules/oe_list_pages_filters_test/config/install/search_api.index.node.yml
- tests/src/FunctionalJavascript/FacetsFormTest.php
- tests/src/Kernel/FulltextWidgetTest.php
- tests/src/Kernel/ListsSourceBaseTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-331: Keyword filter should not be case sensitive

- src/Plugin/ExtraField/Display/ListPageFilters.php
- src/Plugin/ExtraField/Display/ListPageSelectedFilters.php
- src/Plugin/ExtraField/Display/ListPageTotalCount.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-000: Fix namepace for base extra field classes.

- CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-0000: Preparing for 0.2.0 release.

- composer.json
Update facets module to 1.6
- Added:
- Changed: Update facets module to 1.6
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-0: Update facets module.

- composer.json
- oe_list_pages.services.yml
- src/Form/ListPageConfigurationSubForm.php
- src/Form/ListPageConfigurationSubformFactory.php
- src/ListBuilder.php
- src/ListExecutionManager.php
- src/ListExecutionManagerInterface.php
- src/ListExecutionResults.php
- src/ListExecutionResultsInterface.php
- src/ListPageConfiguration.php
- src/ListPageConfigurationFactoryInterface.php
- src/ListPageConfigurationSubformInterface.php
- src/Plugin/EntityMetaRelation/ListPage.php
- src/Plugin/ExtraField/Display/ListPageTotalCount.php
- tests/src/FunctionalJavascript/ListPagesExposedFiltersTest.php
- tests/src/FunctionalJavascript/ListPagesFiltersTest.php
- tests/src/FunctionalJavascript/ListPagesPluginTest.php
- tests/src/Kernel/DateStatusTest.php
- tests/src/Kernel/DateWidgetTest.php
- tests/src/Kernel/FulltextWidgetTest.php
- tests/src/Kernel/ListsEntityMetaTest.php
- tests/src/Kernel/ListsQueryTest.php
- tests/src/Kernel/ListsSourceTest.php
- tests/src/Kernel/ListsSourceTestBase.php
- tests/src/Kernel/MultiSelectWidgetTest.php
This PR refactors the list page configuration form to its own independent subform that can also be used elsewhere.
> EWPP-491: List pages configuration subform.

- src/EventSubscriber/QuerySubscriber.php
- src/ListBuilder.php
- src/ListExecutionManager.php
- src/ListPresetFilter.php
- src/ListPresetFiltersBuilder.php
- src/ListQueryOptionsInterface.php
- src/Plugin/facets/query_type/Fulltext.php
- src/Plugin/facets/widget/DateWidget.php
- src/Plugin/facets/widget/FulltextWidget.php
- src/Plugin/facets/widget/ListPagesWidgetBase.php
- src/Plugin/facets/widget/ListPagesWidgetInterface.php
- src/Plugin/facets/widget/MultiselectWidget.php
- tests/modules/oe_list_pages_filters_test/config/install/field.storage.node.field_reference.yml
- tests/src/FunctionalJavascript/ListPagesPresetFiltersTest.php
- tests/src/Kernel/DateStatusTest.php
- tests/src/Kernel/DateWidgetTest.php
- tests/src/Kernel/FulltextWidgetTest.php
- tests/src/Kernel/ListsQueryTest.php
- tests/src/Kernel/ListsSourceTestBase.php
- tests/src/Kernel/MultiSelectWidgetTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-470: Filter operators

- .gitignore
- CHANGELOG.md
- oe_list_pages.services.yml
- src/Annotation/MultiselectFilterField.php
- src/FacetManipulationTrait.php
- src/MultiSelectFilterFieldPluginBase.php
- src/MultiselectFilterFieldPluginInterface.php
- src/MultiselectFilterFieldPluginManager.php
- src/Plugin/MultiselectFilterField/BooleanField.php
- src/Plugin/MultiselectFilterField/EntityReferenceField.php
- src/Plugin/MultiselectFilterField/LinkField.php
- src/Plugin/MultiselectFilterField/ListField.php
- src/Plugin/facets/widget/ListPagesWidgetBase.php
- src/Plugin/facets/widget/MultiselectWidget.php
- tests/src/Kernel/MultiSelectFilterFieldPluginTest.php
- tests/src/Kernel/MultiSelectWidgetTest.php
Update epic branch.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> Update rss epic

- src/Controller/ListPageRssController.php
- src/FacetManipulationTrait.php
- src/ListExecutionManager.php
- src/Plugin/MultiselectFilterField/EntityReferenceField.php
- tests/src/FunctionalJavascript/ListPageRssControllerTest.php
Improve basic RSS information and multilingual capacity
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-455: Improve basic RSS information and multilingual capacity

- modules/oe_list_pages_open_vocabularies/src/SearchApiConfigurator.php
- modules/oe_list_pages_open_vocabularies/tests/src/Kernel/ListPagesSearchApiConfiguratorTest.php
- src/ListSourceFactory.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-825: Fix weight of created facets

- CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-0000: Preparing for release.

- CHANGELOG.md
Prepare release 0.8.0.
- Added:
- Changed: Update changelog 0.8.0
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> Prepare release 0.8.0.

- modules/oe_list_pages_link_list_source/src/Plugin/LinkSource/ListPageLinkSource.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-901: Restricting the list page link source to the Dynamic bundle.

- CHANGELOG.md
Update changelog for 0.12.0.
- Added:
- Changed: Update changelog for 0.12.0.
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> Prepare release 0.12.0.

- CHANGELOG.md
Prepare release 0.14.0.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> Prepare release 0.14.0.

- composer.json
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-2035: Use new release of link lists component.

- CHANGELOG.md
Prepare release 0.16.0.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> Prepare release 0.16.0.

- modules/oe_list_pages_link_list_source/src/ContextualFilterValuesProcessor.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-2100: Handle empty route context.

- translations/oe_list_pages-uk.po
- translations/oe_list_pages-zh-hans.po
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-2101: Add translation for uk and zh languages.

- translations/oe_list_pages-ru.po
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-2125: Add translation for ru language.

- CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> Prepare release 0.17.0.

- modules/oe_list_pages_open_vocabularies/src/SearchApiConfigurator.php
- src/Plugin/facets/facet_source/ListFacetSourceDeriver.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-2393: Improve support for active indexes used for list pages.

- CHANGELOG.md
- composer.json
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> Prepare release 0.19.0.

- src/Plugin/MultiselectFilterField/EntityReferenceField.php
Fixes #103 
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> Issue #103: Prevent passing a null variable when loading entity reference labels.

- oe_list_pages.module
- tests/src/FunctionalJavascript/ListPageIndexFormTest.php
Fixes issue #150
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> Issue #150: Fix third party options not being saved for indexes.

- CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> Prepare release 0.20.0.

- modules/oe_list_pages_link_list_source/src/Plugin/LinkSource/ListPageLinkSource.php
- modules/oe_list_pages_link_list_source/tests/src/Kernel/ListPageLinkSourcePluginTest.php
- src/Controller/ListPageRssController.php
- src/ListBuilder.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-2618: Change cache tag for lists.

- CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> Prepare release 0.21.0.

- src/Plugin/MultiselectFilterField/EntityReferenceField.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-2919: Check entity id validity before loading.

- oe_list_pages.module
- src/Controller/ListPageRssController.php
- templates/oe-list-pages-rss-item.html.twig
- tests/src/FunctionalJavascript/ListPageRssControllerTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-3696: Add atom:id element for RSS generation for list pages.

- .drone.yml
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> OEL-3050: Update to Drupal 10.3

- src/Plugin/facets/query_type/Fulltext.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-4747: Add support of unstemmed fulltext fields.

- .drone.yml
- docker-compose.yml
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
> EWPP-5553: Update sparql image in docker-compose.yml and .drone.yml.

- config/schema/oe_list_pages.schema.yml
> EPHEH-625: Make upcoming and past labels translatable.
